services:
  postgres:
    image: postgres:15
    build: .
    # profiles: [ "dev", "pro" ]
    #
    environment:
      - POSTGRES_USER=softwaredev
      - POSTGRES_PASSWORD=Lenhutanh2501
      - POSTGRES_DB=ecotechgroup_erp
      - PGDATA=/var/lib/postgresql/data/pgdata

    ports:
      - 8888:5432

    volumes:
      - postgres-dev:/var/lib/postgresql/data

    networks:
      - dev-env

  redis:
    image: redis:7.2.3
    build: .
    ports:
      - 6379:6379
    networks:
      - dev-env
#     secrets:
#       - my_secret
# secrets:
#   my_secret:
#     file: ./my_secret.txt

volumes:
  postgres-dev:
    external: true # reference volume already exist
  redis-dev:
    external: true
  
networks:
  dev-env:
    external: true
